version: '3'

services:
  name: nginx-prometheus-exporter
  image: nginx/nginx-prometheus-exporter:0.10.0
  ports:
    - 9114:9113
  deploy:
    mode: replicated
    replicas: 3
    resources:
      limits:
        cpus: '0.5'
        memory: 500M
        pids: 1
      reservations:
        cpus: '0.25'
        memory: 50M